/*
 Navicat Premium Data Transfer

 Source Server         : 本地数据库
 Source Server Type    : MySQL
 Source Server Version : 50726
 Source Host           : localhost:3306
 Source Schema         : xqoo_nacos_config

 Target Server Type    : MySQL
 Target Server Version : 50726
 File Encoding         : 65001

 Date: 05/01/2021 09:15:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 251 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (20, 'xqoo-cloud-gateway.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 8080\r\nspring:\r\n    cloud:\r\n        gateway:\r\n            discovery:\r\n                locator:\r\n                    enabled: true\r\n                    lowerCaseServiceId: true\r\n            routes:\r\n            -   filters:\r\n                - StripPrefix=1\r\n                id: gatewayOther\r\n                predicates:\r\n                - Path=/OtherClient/**\r\n                uri: https://www.baidu.con/\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_console?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 11', '1c7c626483430450f3fdf30ba29624bf', '2020-10-22 15:41:54', '2020-11-28 00:46:32', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '网关配置', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (24, 'xqoo-client.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 9005\r\nspring:\r\n    redis:\r\n        database: 6\r\n        host: 127.0.0.1', '056ea911e69c710f540e4ab52f83f468', '2020-11-18 15:54:34', '2020-12-05 17:53:59', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (34, 'xqoo-spring-admin-watch.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 8099\r\nspring:\r\n    security:\r\n        basic:\r\n            enable: false\r\n        user:\r\n            name: admin\r\n            password: \"!@#123qwe\"\r\n    redis:\r\n        database: 14', '526fca1a078755ba3d6b3ccbc22be976', '2020-11-18 17:35:59', '2020-12-02 14:02:21', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (87, 'xqoo-cloud-gateway-api-sentinel', 'SENTINEL_GROUP', '[{\"apiName\":\"xqoo-client-test\",\"app\":\"xqoo-cloud-gateway\",\"gmtCreate\":1605879328754,\"gmtModified\":1605879328754,\"id\":1,\"ip\":\"192.168.0.107\",\"port\":8721,\"predicateItems\":[{\"matchStrategy\":1,\"pattern\":\"/client/hello/**\"}]},{\"apiName\":\"xqoo-client\",\"app\":\"xqoo-cloud-gateway\",\"gmtCreate\":1605879369315,\"gmtModified\":1605879369315,\"id\":2,\"ip\":\"192.168.0.107\",\"port\":8721,\"predicateItems\":[{\"matchStrategy\":1,\"pattern\":\"/client/helloworld/**\"}]}]', '89b6eb73d8e8aa48dfd30d80f7a5bb92', '2020-11-20 19:36:09', '2020-11-20 21:36:34', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (119, 'xqoo-cloud-gateway-flwo-sentinel', 'SENTINEL_GROUP', '[{\"app\":\"xqoo-cloud-gateway\",\"burst\":0,\"controlBehavior\":0,\"count\":5.0,\"gmtCreate\":1605882011954,\"gmtModified\":1605882011954,\"grade\":1,\"id\":1,\"interval\":1,\"intervalUnit\":0,\"ip\":\"192.168.0.107\",\"port\":8721,\"resource\":\"xqoo-client\",\"resourceMode\":1}]', 'a4efb42db8fdcdaf3cdea8d67be9a871', '2020-11-20 22:20:12', '2020-11-20 22:20:12', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (120, 'xqoo-cloud-gateway-degrade-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:20:44', '2020-11-20 22:23:05', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (121, 'xqoo-cloud-gateway-system-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:20:58', '2020-11-20 22:23:01', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (122, 'sentinel-dashboard-param-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:21:59', '2020-11-20 22:22:47', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (123, 'sentinel-dashboard-thority-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:22:19', '2020-11-20 22:22:37', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (128, 'xqoo-client-flwo-sentinel', 'SENTINEL_GROUP', '[\n	{\n		\"clusterConfig\":{\n			\"fallbackToLocalWhenFail\":true,\n			\"sampleCount\":10,\n			\"strategy\":0,\n			\"thresholdType\":0,\n			\"windowIntervalMs\":1000\n		},\n		\"clusterMode\":false,\n		\"controlBehavior\":0,\n		\"count\":3.0,\n		\"grade\":1,\n		\"limitApp\":\"default\",\n		\"maxQueueingTimeMs\":500,\n		\"resource\":\"xqoo-test-one\",\n		\"strategy\":0,\n		\"warmUpPeriodSec\":10\n	},\n	{\n		\"clusterConfig\":{\n			\"fallbackToLocalWhenFail\":true,\n			\"sampleCount\":10,\n			\"strategy\":0,\n			\"thresholdType\":0,\n			\"windowIntervalMs\":1000\n		},\n		\"clusterMode\":false,\n		\"controlBehavior\":0,\n		\"count\":2.0,\n		\"grade\":1,\n		\"limitApp\":\"default\",\n		\"maxQueueingTimeMs\":500,\n		\"resource\":\"xqoo-test-two\",\n		\"strategy\":0,\n		\"warmUpPeriodSec\":10\n	}\n]', '1ddfb13fb523b84218616a86abf20086', '2020-11-20 22:23:33', '2020-11-20 22:24:03', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (130, 'xqoo-client-param-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:24:25', '2020-11-20 22:24:28', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (132, 'xqoo-client-thority-sentinel', 'SENTINEL_GROUP', '[]', 'd751713988987e9331980363e24189ce', '2020-11-20 22:24:37', '2020-11-20 22:24:43', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `config_info` VALUES (134, 'xqoo-client-degrade-sentinel', 'SENTINEL_GROUP', '[{\"app\":\"xqoo-client\",\"count\":1000.0,\"gmtCreate\":1605882394823,\"gmtModified\":1605882444233,\"grade\":0,\"id\":2,\"ip\":\"192.168.0.107\",\"limitApp\":\"default\",\"minRequestAmount\":1,\"port\":8720,\"resource\":\"xqoo-test-two\",\"slowRatioThreshold\":0.1,\"statIntervalMs\":1000,\"timeWindow\":1}]', '4bf1d5c9b5e8a11c3b19eb5148bb838e', '2020-11-20 22:26:35', '2020-11-21 09:54:47', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', '', '');
INSERT INTO `config_info` VALUES (138, 'xqoo-cloud-authorization.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 9011\r\nspring:\r\n    datasource:\r\n        druid:\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_console?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    redis:\r\n        database: 12', 'cc8389bea01dfd5eee2310b8ae161854', '2020-11-21 13:48:12', '2020-11-23 16:48:00', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (140, 'xqoo-uid-generator.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 9003\r\n    tomcat:\r\n        acceptCount: 2000\r\n        max-connections: 20000\r\n        max-threads: 1000\r\n        min-SpareThreads: 20\r\n        uri-encoding: UTF-8\r\nspring:\r\n    datasource:\r\n        druid:\r\n            password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_console?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia%2fShanghai\r\n            username: root\r\n    redis:\r\n        database: 4', '3710b8a1b63132ba8b8b671fdfd5c4ef', '2020-11-21 14:15:37', '2020-11-23 14:10:40', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (195, 'module-share-config.yml', 'PUBLIC_CONFIG_GROUP', 'spring:\r\n    zipkin:\r\n        base-url: http://127.0.0.1:9411\r\n        sender:\r\n            type: web\r\n    #设置Sleuth的抽样收集概率,1=100%,因为我们目前是测试环境所以用1\r\n    sleuth:\r\n        sampler:\r\n            probability: 1\r\n#请求处理的超时时间\r\nribbon:\r\n    ReadTimeout: 10000\r\n    ConnectTimeout: 10000\r\n# 服务内部消费接口\r\nfeign:\r\n    client:\r\n        config:\r\n            default:\r\n                connectTimeout: 10000\r\n                loggerLevel: basic\r\n                readTimeout: 10000\r\n    compression:\r\n        request:\r\n            enabled: true\r\n            mime-types: text/xml,application/xml,application/json\r\n            min-request-size: 2048\r\n        response:\r\n            enabled: true\r\n    sentinel:\r\n        enabled: true\r\n    okhttp:\r\n        enabled: true\r\n    httpclient: \r\n        enabled: false\r\n# 暴露监控端点\r\nmanagement:\r\n    endpoint:\r\n        health:\r\n            show-details: always\r\n    endpoints:\r\n        web:\r\n            exposure:\r\n                include: \'*\'', '3052bd9c58a396799676c7cf18959048', '2020-11-23 13:44:14', '2020-11-30 21:29:12', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (199, 'public-redis-config.yml', 'PUBLIC_CONFIG_GROUP', 'spring:\r\n    redis:\r\n        database: 1\r\n        host: 127.0.0.1\r\n        lettuce:\r\n            pool:\r\n                max-active: 100\r\n                max-idle: 10\r\n                max-wait: 20000\r\n                min-idle: 1  \r\n        password: A123456bexqoo                    \r\n        port: 6379\r\n        timeout: 10000\r\n        # 最大重定向次数，不能超过节点总数，用以限制访问失败后转其他节点访问限制，集群属性，单点无视\r\n        max-redirects: 3\r\n        # 集群节点扫描间隔，单位毫秒\r\n        scan-interval: 1000\r\n        # 此项为集群redis节点地址，不是集群忽略即可，注意下方key和值之间不能有空格\r\n        cluster-node:\r\n            - node-host: 127.0.0.1\r\n              node-port: 6379\r\n            - node-host: 192.168.0.106\r\n              node-port: 6379', 'fa03901ca91b91d36f24a54b6ed5306e', '2020-11-23 13:57:16', '2020-11-23 14:30:56', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (202, 'public-mysql-config.yml', 'PUBLIC_CONFIG_GROUP', 'spring:\r\n    datasource:\r\n        driverClassName: com.mysql.cj.jdbc.Driver\r\n        druid:\r\n            filter:\r\n                stat:\r\n                    enabled: true\r\n                    log-slow-sql: true\r\n                    merge-sql: true\r\n                    slow-sql-millis: 1000\r\n                wall:\r\n                    config:\r\n                        multi-statement-allow: true\r\n            initialSize: 5\r\n            maxActive: 20\r\n            maxEvictableIdleTimeMillis: 900000\r\n            maxWait: 60000\r\n            minEvictableIdleTimeMillis: 300000\r\n            minIdle: 10\r\n            password: gao2236\r\n            statViewServlet:\r\n                enabled: true\r\n            testOnBorrow: false\r\n            testOnReturn: false\r\n            testWhileIdle: true\r\n            timeBetweenEvictionRunsMillis: 60000\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_console?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            username: root\r\n            validationQuery: SELECT 1 FROM DUAL\r\n            webStatFilter:\r\n                enabled: true\r\n        type: com.alibaba.druid.pool.DruidDataSource', '3848787208efd22339ce47be6d35796a', '2020-11-23 13:58:21', '2020-11-23 13:58:53', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (212, 'public-xqoo-config.yml', 'PUBLIC_CONFIG_GROUP', 'xqoo:\r\n  auth:\r\n    # jwt 加密秘钥\r\n    jwt-secret-key: secretKey:88945.939\r\n    # jwt令牌默认失效时间，实际可根据程序中自定，单位s\r\n    jwt-expire: 600\r\n    # token失效，单位s\r\n    token-expire: 10000\r\n    # token 刷新时间，小于此时间时刷新token持续时间，单位 s, \r\n    # 为0时表示不刷新，到期即失效token\r\n    # 最小60，最大不超过失效时间一半\r\n    token-refresh-limit: 6000\r\n    # 是否开启时区校验，不同时区账号不允许登录\r\n    time-zone-check: true\r\n    # 时间误差，当登录请求发送时间与服务器接收时间超过此误差值时，不允许登录，关闭时区校验后此项不可用，单位：秒\r\n    time-exact: 30\r\n    # 单一登录限制,true为开启单一登录，一处登录登出其他地方\r\n    login-single: true\r\n    # 单一登录类型，all-为全平台不论登录来源，source-每个来源只能登录一个\r\n    login-single-type: all \r\n    # 是否开启登录错误次数过多锁定\r\n    login-err-lock: \r\n      active: true\r\n      # 最大错误次数 小于等于0为不限制\r\n      max-error-time: 8\r\n      # 错误锁定时间 分钟，-1则为不自动解锁\r\n      lock-time: 30\r\n      # 密码错误几次开启验证， 0和-1表示不开启\r\n      need-check-error-time: 3\r\n      # 错误验证码失效时间 分钟, 小于等于0时默认5分钟\r\n      error-code-expire: 5\r\n    # 登录方式开开关\r\n    login-type-switch:\r\n      # 账号密码模式\r\n      - type: PASSWORD\r\n        active: true\r\n        # 邮件模式\r\n      - type: EMAIL\r\n        active: false\r\n      # 面部识别模式\r\n      - type: FACE\r\n        active: false\r\n      # 指纹识别模式\r\n      - type: FINGER\r\n        active: false\r\n      # QRCODE模式\r\n      - type: QRCODE\r\n        active: false\r\n      # 手机验证码模式\r\n      - type: PHONE\r\n        active: false\r\n      # 第三方登录模式\r\n      - type: THIRDPARTY\r\n        active: false\r\n  secret:\r\n    # aes加密的秘钥，必须16位，否则会报错\r\n    aes-key: EbQT9S2Ou-Lm3Oq0', '5bbb02f9d6186ea34277799f062e5c5a', '2020-11-23 16:47:22', '2020-12-29 10:49:07', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (245, 'public-xqoo-gateway-config.yml', 'PUBLIC_CONFIG_GROUP', 'xqoo:\r\n  gateway:\r\n    # 目标黑名单域名，ip或路径，支持通配符, 没有host或path不填即可\r\n    target-black-list:  \r\n      - host: \'www.baidu.con\'\r\n        path: \'/*\'\r\n      - path: \'/helloworld/**\'\r\n    # ip来源黑名单, host必须有，port可以是多个，支持通配符\r\n    remote-black-list:\r\n      - host: \'192.168.0.3\'\r\n        port: \r\n          - \'**\'\r\n    # 不需要登录的路径，支持通配符\r\n    no-login-filter:\r\n      - path: /v2/api-docs/**\r\n      - path: /author/**\r\n    # 系统占用的返回状态，不做统一拦截\r\n    filter-http-status:\r\n      - status-code: 400\r\n        reason: 请求资源已失效\r\n      - status-code: 401\r\n        reason: 请求资源需要登录\r\n      - status-code: 402\r\n        reason: 请求资源需要付费\r\n      - status-code: 404\r\n        reason: 请求资源未找到\r\n      - status-code: 405\r\n        reason: 提交方式不正确或表单数据验证不通过\r\n      - status-code: 406\r\n        reason: 请求不予以通过\r\n      - status-code: 408\r\n        reason: 请求超时\r\n      - status-code: 412\r\n        reason: 密码输入错误次数过多\r\n      - status-code: 421\r\n        reason: 当前请求人已停用\r\n      - status-code: 423\r\n        reason: 请求来源账户已冻结或被锁定\r\n      - status-code: 429\r\n        reason: 请求次数过于频繁\r\n      - status-code: 502\r\n        reason: 请求的地址错误\r\n      - status-code: 504\r\n        reason: 请求地址访问超时\r\n      - status-code: 510\r\n        reason: 请求来源ip已被拉黑\r\n      - status-code: 511\r\n        reason: 请求地址已被拉黑', '0a9c244e54bceecbc2c0296a74a4f404', '2020-11-28 13:38:18', '2020-12-05 12:26:59', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (246, 'xqoo-cloud-operation-log.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 9018\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_operation_log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root', '235b967397c4114ef0b613e73c614d63', '2020-11-30 13:01:56', '2020-11-30 13:02:31', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (247, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:/home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm\r\n        - label: microService\r\n          value: microService\r\n          type: microService\r\n          url:\r\n            - vm/microServiceTemplate/src/main/java/com/xqoo/Application.java.vm\r\n            - vm/microServiceTemplate/src/main/resource/bootstrap.yml.vm\r\n            - vm/microServiceTemplate/src/main/resource/logback-spring.xml.vm\r\n            - vm/microServiceTemplate/Dockerfile.vm\r\n            - vm/microServiceTemplate/nacos-application.yml.vm\r\n            - vm/microServiceTemplate/readme.md.vm\r\n            - vm/microServiceTemplate/pom.xml.vm\r\n        - label: singleEntity\r\n          value: singleEntity\r\n          type: singleEntity\r\n          url:\r\n            - vm/java/singleEntity.java.vm', '27363a2115eb9fef4112d4a0cbfd4b25', '2020-12-23 11:36:19', '2021-01-04 18:31:02', NULL, '127.0.0.1', '', 'xqoo-cloud-namespace-asdfghjk-dev', '', '', '', 'yaml', '');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 334 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (0, 313, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9018\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_operation_log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root', '235b967397c4114ef0b613e73c614d63', '2020-12-23 11:36:18', '2020-12-23 11:36:19', NULL, '127.0.0.1', 'I', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 314, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9018\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_system_operation_log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root', '235b967397c4114ef0b613e73c614d63', '2020-12-23 11:37:40', '2020-12-23 11:37:40', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 315, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1', '65d9997dc3c5196f981f90f79aa6a3af', '2020-12-23 13:43:29', '2020-12-23 13:43:29', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 316, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ndata-base-type:\r\n    - type: mysql\r\n      driver: com.mysql.jdbc.Driver\r\n      prefix: jdbc:mysql://\r\n      port: 3306\r\n      properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8', '36e8776d77fd8d9ec5f90dbcc9c2ed0e', '2020-12-23 13:54:11', '2020-12-23 13:54:11', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (212, 317, 'public-xqoo-config.yml', 'PUBLIC_CONFIG_GROUP', '', 'xqoo:\r\n  auth:\r\n    # jwt 加密秘钥\r\n    jwt-secret-key: secretKey:88945.939\r\n    # jwt令牌默认失效时间，实际可根据程序中自定，单位s\r\n    jwt-expire: 600\r\n    # token失效，单位s\r\n    token-expire: 10000\r\n    # token 刷新时间，小于此时间时刷新token持续时间，单位 s, \r\n    # 为0时表示不刷新，到期即失效token\r\n    # 最小60，最大不超过失效时间一半\r\n    token-refresh-limit: 6000\r\n    # 单一登录限制,true为开启单一登录，一处登录登出其他地方\r\n    login-single: true\r\n    # 单一登录类型，all-为全平台不论登录来源，source-每个来源只能登录一个\r\n    login-single-type: all \r\n    # 是否开启登录错误次数过多锁定\r\n    login-err-lock: \r\n      active: true\r\n      # 最大错误次数 小于等于0为不限制\r\n      max-error-time: 8\r\n      # 错误锁定时间 分钟，-1则为不自动解锁\r\n      lock-time: 30\r\n      # 密码错误几次开启验证， 0和-1表示不开启\r\n      need-check-error-time: 3\r\n      # 错误验证码失效时间 分钟, 小于等于0时默认5分钟\r\n      error-code-expire: 5\r\n    # 登录方式开开关\r\n    login-type-switch:\r\n      # 账号密码模式\r\n      - type: PASSWORD\r\n        active: true\r\n        # 邮件模式\r\n      - type: EMAIL\r\n        active: false\r\n      # 面部识别模式\r\n      - type: FACE\r\n        active: false\r\n      # 指纹识别模式\r\n      - type: FINGER\r\n        active: false\r\n      # QRCODE模式\r\n      - type: QRCODE\r\n        active: false\r\n      # 手机验证码模式\r\n      - type: PHONE\r\n        active: false\r\n      # 第三方登录模式\r\n      - type: THIRDPARTY\r\n        active: false\r\n  secret:\r\n    # aes加密的秘钥，必须16位，否则会报错\r\n    aes-key: EbQT9S2Ou-Lm3Oq0', 'b9177c8f773c792e794a959b527da6dd', '2020-12-29 10:49:06', '2020-12-29 10:49:07', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 318, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8', '55f080e50c9740b37d0d8b4a5813a5c5', '2020-12-29 15:58:12', '2020-12-29 15:58:12', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 319, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '1872fe663cf7f0a5688867df6a99ed3e', '2020-12-29 16:04:12', '2020-12-29 16:04:12', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 320, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen|any\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', 'f6a1e57dabc9136eafb7930ef1a8ff27', '2020-12-29 16:26:46', '2020-12-29 16:26:47', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 321, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen|any\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', 'f6a1e57dabc9136eafb7930ef1a8ff27', '2020-12-29 16:40:35', '2020-12-29 16:40:35', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 322, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: any\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: ooo\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '21a83684e37835c7818d2e95a7ea8162', '2020-12-29 16:44:57', '2020-12-29 16:44:58', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 323, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', 'c9270b4d3f6ef6e561bdd8662f4787d0', '2020-12-30 10:27:47', '2020-12-30 10:27:47', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 324, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: /home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '8ae62517bffce4eea1cfa4f5884578b1', '2020-12-30 11:37:59', '2020-12-30 11:37:59', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 325, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:\\home\\codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '5230e6588b53befd07015f6a278db39f', '2020-12-30 11:46:29', '2020-12-30 11:46:29', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 326, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: \\home\\codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', 'bd5e138c360e57078e949d75a37d9017', '2020-12-30 11:49:58', '2020-12-30 11:49:58', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 327, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:\\home\\codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '5230e6588b53befd07015f6a278db39f', '2020-12-30 12:10:32', '2020-12-30 12:10:33', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 328, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:\\\\home\\\\codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', 'd0d92da460f00b9cf2fff750dae9b0c6', '2020-12-30 12:30:33', '2020-12-30 12:30:33', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 329, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '6c03deedc199571652f5a60574f74bc5', '2020-12-30 12:57:21', '2020-12-30 12:57:22', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 330, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:/home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm', '566f7f8acb103b0b34582ac351c1ef28', '2020-12-31 14:50:40', '2020-12-31 14:50:40', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 331, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:/home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm\r\n        - label: microService\r\n          value: microService\r\n          type: microService\r\n          url:\r\n            - vm/microServiceTemplate/src/main/java/com/xqoo/Application.java.vm\r\n            - vm/microServiceTemplate/src/main/resource/bootstrap.yml.vm\r\n            - vm/microServiceTemplate/src/main/resource/logback-spring.xml.vm\r\n            - vm/microServiceTemplate/Dockerfile.vm\r\n            - vm/microServiceTemplate/pom.xml.vm', '28ae5590accccf9de690fae375075f7b', '2021-01-04 15:02:31', '2021-01-04 15:02:31', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 332, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:/home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm\r\n        - label: microService\r\n          value: microService\r\n          type: microService\r\n          url:\r\n            - vm/microServiceTemplate/src/main/java/com/xqoo/Application.java.vm\r\n            - vm/microServiceTemplate/src/main/resource/bootstrap.yml.vm\r\n            - vm/microServiceTemplate/src/main/resource/logback-spring.xml.vm\r\n            - vm/microServiceTemplate/Dockerfile.vm\r\n            - vm/microServiceTemplate/nacos-application.yml.vm\r\n            - vm/microServiceTemplate/readme.md.vm\r\n            - vm/microServiceTemplate/pom.xml.vm', 'a021e813b8be3ac25c5a2e6c9f0e9f8e', '2021-01-04 18:11:06', '2021-01-04 18:11:06', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');
INSERT INTO `his_config_info` VALUES (247, 333, 'xqoo-cloud-code-generator.yml', 'DEFAULT_GROUP', '', 'server:\r\n    port: 9009\r\nspring:\r\n    datasource:\r\n        druid:\r\n            # 使用默认连接属性请酌情注释此三项\r\n            #password: gao2236\r\n            url: jdbc:mysql://127.0.0.1:3306/xqoo_code_generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n            #username: root\r\n    redis:\r\n        database: 1\r\ncode-gen:\r\n    download-base-path: D:/home/codeGen\r\n    default-author: xqoo-code-gen\r\n    data-base-type:\r\n        - type: mysql\r\n          driver: com.mysql.jdbc.Driver\r\n          prefix: jdbc:mysql://\r\n          port: \'3306\'\r\n          properties: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8\r\n    template:\r\n        - label: controller.java\r\n          value: controller.java\r\n          # 主要用于生成不同代码获取模板不同时展示，多个类型用|隔开，any表示所有类型都显示此模板\r\n          type: tableGen\r\n          # url只实际模板相对路径，一个模板类型可包含多个模板路径\r\n          url: \r\n            - vm/java/controller.java.vm\r\n        - label: service.java\r\n          value: service.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/service.java.vm\r\n            - vm/java/serviceImpl.java.vm\r\n        - label: entity.java\r\n          value: entity.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/entity.java.vm\r\n        - label: mapper.java\r\n          value: mapper.java\r\n          type: tableGen\r\n          url: \r\n            - vm/java/mapper.java.vm\r\n        - label: mapper.xml\r\n          value: mapper.xml\r\n          type: tableGen\r\n          url: \r\n            - vm/xml/mapper.xml.vm\r\n        - label: microService\r\n          value: microService\r\n          type: microService\r\n          url:\r\n            - vm/microServiceTemplate/src/main/java/com/xqoo/Application.java.vm\r\n            - vm/microServiceTemplate/src/main/resource/bootstrap.yml.vm\r\n            - vm/microServiceTemplate/src/main/resource/logback-spring.xml.vm\r\n            - vm/microServiceTemplate/Dockerfile.vm\r\n            - vm/microServiceTemplate/nacos-application.yml.vm\r\n            - vm/microServiceTemplate/readme.md.vm\r\n            - vm/microServiceTemplate/pom.xml.vm\r\n        - label: singelEntity\r\n          value: singelEntity\r\n          type: singelEntity\r\n          url:\r\n            - vm/java/singleEntity.java.vm', '35a0d75bc64480b721875f41f00da53a', '2021-01-04 18:31:01', '2021-01-04 18:31:02', NULL, '127.0.0.1', 'U', 'xqoo-cloud-namespace-asdfghjk-dev');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `resource` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (1, '1', 'xqoo-cloud-namespace-asdfghjk-dev', 'xqoo-cloud-namespace-asdfghjk-dev', '兴黔微服务nacos配置中心', 'nacos', 1603349748837, 1603349748837);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
